language: node_js
node_js:
  - "14"
cache:
  directories:
    - node_modules
branches:
  only:
  - test
jobs:
  include:
    - stage: Lint, Test, Build
      name: Lint
      script:
        - cd client
        - npm install
        - npm run lint
    - name: Test
      if: branch = test
      script:
        - cd client
        - npm install
        - npm run test:coverage
    - name: Build
      script:
        - cd client
        - npm install
        - npm run build
